### ISSUE TITLE
Problem with "The TAO"

### ISSUE THREAD

**Issue by taoeffect** [makerdao/simplecoin#3]
Dear Nikolai, I would love to support your project, but please consider this small tiny request that makes it difficult for me to do so: the word "Tao" has a [well established meaning](https://en.wikipedia.org/wiki/Tao) in English.

In fact it is spelled in two ways, one is Tao, the other is Dao.

The Tao is a meaningful term in the philosophy of Taoism, a philosophy that I personally really like and respect.

It was somewhat upsetting to me when "The DAO" came along and named itself after, essentially, the "most fundamental thing in the universe". And it ended up tarnishing that word beyond even my wildest expectations.

It would be upsetting to a lot of people, not just me, if this was done with "The TAO" as well. So, out of respect for this ancient philosophy/way/religion/practice, could you please consider _not_ linking or mentioning any such thing as "The TAO" in your documentation?

Thank you very much for considering this! I wish you all the best of luck with your projects!

**Comment by taoeffect** [comment]
Oh, and yes, I just realized it is also a term that appears in my username. So that doesn't help either. :P

**Comment by nmushegian** [comment]
Hi greg! Thanks for this issue.

"The TAO" is a direct jab at The DAO's insistence on using that term despite our warnings. We were unhappy with them because there were several DAOs prior to "The" DAO, and we're also upset that the term's reputation is tarnished - just from another angle.

I think daoism is wonderful and it's in a cluster of belief systems I find very compelling. I happen to have great respect for it, although I don't think something being ancient or widespread or someone's religion is a reason to respect something a priori.

Anyway I think this request sounds a lot like calling someone out for naming their kid "Jesus".

That said, if the owner of the project changes the name, I'll happily update the docs to match:  https://github.com/ryepdx/the-tao

**Comment by taoeffect** [comment]
> Anyway I think this request sounds a lot like calling someone out for naming their kid "Jesus".

More like "Science" or "The Science". It's nonsensical and tarnishes the concept of science. I mean, how would you feel if people were turned off of science because some project decided to name themselves, "Science" and made it synonymous with "scam"?

It makes the creators of this thing (_cough_ @ryepdx) look foolish, and generally stirs a pot that doesn't need stirring. But do as you will.

**Comment by taoeffect** [comment]
Unless I misunderstood and you're saying the "The TAO" thing is _intended_ as a joke and a jab for the specific purpose of _not_ naming things like this. In which case it would be super awesome if that could be made clearer in the README here, because otherwise it is not a jab but just doing the same exact thing.
